// GENERATED by scripts/build_presets.py — do not hand-edit.
export default {
  "generated": "scripts/build_presets.py — do not hand-edit",
  "duel": [
    {
      "slug": "archipelago-land-lg-water-sm-smallest-square-sym",
      "group": "Archipelago",
      "variant": "Land Lg · Water Sm",
      "title": "Archipelago",
      "script": "Archipelago",
      "mapClass": "MAPCLASS_MapScriptArchipelago",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_ARCHIPELAGO_LANDMASS",
          "value": "MAP_OPTION_ARCHIPELAGO_LANDMASS_LARGE",
          "label": "Islands Size",
          "valueLabel": "Large"
        },
        {
          "name": "MAP_OPTIONS_MULTI_ARCHIPELAGO_WATER_SIZE",
          "value": "MAP_OPTION_ARCHIPELAGO_WATER_SIZE_MERGED",
          "label": "Water Size",
          "valueLabel": "Small"
        }
      ],
      "art": "img/maps/archipelago.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-archipelago-land-lg-water-sm-smallest-square-sym"
    },
    {
      "slug": "archipelago-land-lg-water-sm-smallest-wide-nosym",
      "group": "Archipelago",
      "variant": "Land Lg · Water Sm",
      "title": "Archipelago",
      "script": "Archipelago",
      "mapClass": "MAPCLASS_MapScriptArchipelago",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_WIDE",
      "aspectLabel": "Wide",
      "pointSymmetry": false,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_ARCHIPELAGO_LANDMASS",
          "value": "MAP_OPTION_ARCHIPELAGO_LANDMASS_LARGE",
          "label": "Islands Size",
          "valueLabel": "Large"
        },
        {
          "name": "MAP_OPTIONS_MULTI_ARCHIPELAGO_WATER_SIZE",
          "value": "MAP_OPTION_ARCHIPELAGO_WATER_SIZE_MERGED",
          "label": "Water Size",
          "valueLabel": "Small"
        }
      ],
      "art": "img/maps/archipelago.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-archipelago-land-lg-water-sm-smallest-wide-nosym"
    },
    {
      "slug": "arid-plateau-small-seas-smallest-square-sym",
      "group": "Arid Plateau",
      "variant": "Small Seas",
      "title": "Small Seas Arid Plateau",
      "script": "Arid Plateau",
      "mapClass": "MAPCLASS_AridPlateau",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_MULTI_ARID_WATER_SIZE",
          "value": "MAP_OPTION_ARID_WATER_SIZE_SMALL",
          "label": "Water Size",
          "valueLabel": "Small"
        }
      ],
      "art": "img/maps/arid-plateau.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-arid-plateau-small-seas-smallest-square-sym"
    },
    {
      "slug": "arid-plateau-large-seas-smallest-square-sym",
      "group": "Arid Plateau",
      "variant": "Large Seas",
      "title": "Large Seas Arid Plateau",
      "script": "Arid Plateau",
      "mapClass": "MAPCLASS_AridPlateau",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_MULTI_ARID_WATER_SIZE",
          "value": "MAP_OPTION_ARID_WATER_SIZE_LARGE",
          "label": "Water Size",
          "valueLabel": "Large"
        }
      ],
      "art": "img/maps/arid-plateau.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-arid-plateau-large-seas-smallest-square-sym"
    },
    {
      "slug": "coastal-rain-basin-smallest-wide-nosym",
      "group": "Coastal Rain Basin",
      "variant": "",
      "title": "Coastal Rain Basin",
      "script": "Coastal Rain Basin",
      "mapClass": "MAPCLASS_CoastalRainBasin",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_WIDE",
      "aspectLabel": "Wide",
      "pointSymmetry": false,
      "mirror": true,
      "opts": [],
      "art": "img/maps/coastal-rain-basin.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-coastal-rain-basin-smallest-wide-nosym"
    },
    {
      "slug": "coastal-rain-basin-smallest-square-sym",
      "group": "Coastal Rain Basin",
      "variant": "",
      "title": "Coastal Rain Basin",
      "script": "Coastal Rain Basin",
      "mapClass": "MAPCLASS_CoastalRainBasin",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [],
      "art": "img/maps/coastal-rain-basin.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-coastal-rain-basin-smallest-square-sym"
    },
    {
      "slug": "continent-smallest-wide-sym",
      "group": "Continent",
      "variant": "",
      "title": "Continent",
      "script": "Continent",
      "mapClass": "MAPCLASS_MapScriptContinent",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_WIDE",
      "aspectLabel": "Wide",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_MULTI_CONTINENT_TERRAIN",
          "value": "MAP_OPTION_CONTINENT_TERRAIN_NONE",
          "label": "Extreme Terrain",
          "valueLabel": "None"
        }
      ],
      "art": "img/maps/continent.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-continent-smallest-wide-sym"
    },
    {
      "slug": "desert-lush-std-tiny-square-nosym",
      "group": "Desert",
      "variant": "Lush · Std",
      "title": "Lush Coast Desert",
      "script": "Desert",
      "mapClass": "MAPCLASS_MapScriptDesert",
      "size": "MAPSIZE_TINY",
      "sizeLabel": "Tiny",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": false,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_DESERT_COAST",
          "value": "MAP_OPTION_DESERT_COAST_LUSH",
          "label": "Desert Coast",
          "valueLabel": "Lush"
        },
        {
          "name": "MAP_OPTIONS_DESERT_SIZE",
          "value": "MAP_OPTION_DESERT_SIZE_NORMAL",
          "label": "Desert Size",
          "valueLabel": "Standard"
        }
      ],
      "art": "img/maps/desert.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-desert-lush-std-tiny-square-nosym"
    },
    {
      "slug": "desert-none-std-tiny-square-sym",
      "group": "Desert",
      "variant": "None · Std",
      "title": "No Coast Desert",
      "script": "Desert",
      "mapClass": "MAPCLASS_MapScriptDesert",
      "size": "MAPSIZE_TINY",
      "sizeLabel": "Tiny",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_DESERT_COAST",
          "value": "MAP_OPTION_DESERT_COAST_NONE",
          "label": "Desert Coast",
          "valueLabel": "None"
        },
        {
          "name": "MAP_OPTIONS_DESERT_SIZE",
          "value": "MAP_OPTION_DESERT_SIZE_NORMAL",
          "label": "Desert Size",
          "valueLabel": "Standard"
        }
      ],
      "art": "img/maps/desert.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-desert-none-std-tiny-square-sym"
    },
    {
      "slug": "donut-irreg-low-smallest-square-sym",
      "group": "Donut",
      "variant": "Irreg Low",
      "title": "Donut",
      "script": "Donut",
      "mapClass": "MAPCLASS_MapScriptDonut",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_DONUT_IRREGULARITY",
          "value": "MAP_OPTION_DONUT_IRREGULARITY_LOW",
          "label": "Donut Irregularity",
          "valueLabel": "Low"
        }
      ],
      "art": "img/maps/donut.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-donut-irreg-low-smallest-square-sym"
    },
    {
      "slug": "dota-jungle-smallest-square-sym",
      "group": "DOTA",
      "variant": "Jungle",
      "title": "Jungle DOTA",
      "script": "Duel of the Ancients",
      "mapClass": "MAPCLASS_MapScriptDota",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_MULTI_DOTA_INNER_TERRAIN",
          "value": "MAP_OPTION_TERRAIN_INNER_JUNGLE",
          "label": "Separating Terrain",
          "valueLabel": "Jungle"
        },
        {
          "name": "MAP_OPTIONS_MULTI_DOTA_OUTER_TERRAIN",
          "value": "MAP_OPTION_TERRAIN_OUTER_JUNGLE",
          "label": "Outer Terrain",
          "valueLabel": "Jungle"
        },
        {
          "name": "MAP_OPTIONS_MULTI_DOTA_PATH_WIDTH",
          "value": "MAP_OPTION_PATH_NARROW",
          "label": "Path Width",
          "valueLabel": "Narrow"
        }
      ],
      "art": "img/maps/dota.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-dota-jungle-smallest-square-sym"
    },
    {
      "slug": "dota-sand-smallest-square-sym",
      "group": "DOTA",
      "variant": "Sand",
      "title": "Sand DOTA",
      "script": "Duel of the Ancients",
      "mapClass": "MAPCLASS_MapScriptDota",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_MULTI_DOTA_INNER_TERRAIN",
          "value": "MAP_OPTION_TERRAIN_INNER_SAND",
          "label": "Separating Terrain",
          "valueLabel": "Sand"
        },
        {
          "name": "MAP_OPTIONS_MULTI_DOTA_OUTER_TERRAIN",
          "value": "MAP_OPTION_TERRAIN_OUTER_SAND",
          "label": "Outer Terrain",
          "valueLabel": "Sand"
        },
        {
          "name": "MAP_OPTIONS_MULTI_DOTA_PATH_WIDTH",
          "value": "MAP_OPTION_PATH_NARROW",
          "label": "Path Width",
          "valueLabel": "Narrow"
        }
      ],
      "art": "img/maps/dota.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-dota-sand-smallest-square-sym"
    },
    {
      "slug": "dota-water-smallest-square-sym",
      "group": "DOTA",
      "variant": "Water",
      "title": "Water DOTA",
      "script": "Duel of the Ancients",
      "mapClass": "MAPCLASS_MapScriptDota",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [
        {
          "name": "MAP_OPTIONS_MULTI_DOTA_INNER_TERRAIN",
          "value": "MAP_OPTION_TERRAIN_INNER_WATER",
          "label": "Separating Terrain",
          "valueLabel": "Water"
        },
        {
          "name": "MAP_OPTIONS_MULTI_DOTA_OUTER_TERRAIN",
          "value": "MAP_OPTION_TERRAIN_OUTER_WATER",
          "label": "Outer Terrain",
          "valueLabel": "Water"
        },
        {
          "name": "MAP_OPTIONS_MULTI_DOTA_PATH_WIDTH",
          "value": "MAP_OPTION_PATH_NARROW",
          "label": "Path Width",
          "valueLabel": "Narrow"
        }
      ],
      "art": "img/maps/dota.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-dota-water-smallest-square-sym"
    },
    {
      "slug": "hardwood-forest-smallest-wide-nosym",
      "group": "Hardwood Forest",
      "variant": "",
      "title": "Hardwood Forest",
      "script": "Hardwood Forest",
      "mapClass": "MAPCLASS_MapScriptHardwoodForest",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_WIDE",
      "aspectLabel": "Wide",
      "pointSymmetry": false,
      "mirror": true,
      "opts": [],
      "art": "img/maps/hardwood-forest.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-hardwood-forest-smallest-wide-nosym"
    },
    {
      "slug": "inland-sea-smallest-square-sym",
      "group": "Inland Sea",
      "variant": "",
      "title": "Inland Sea",
      "script": "Inland Sea",
      "mapClass": "MAPCLASS_MapScriptInlandSea2",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [],
      "art": "img/maps/inland-sea.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-inland-sea-smallest-square-sym"
    },
    {
      "slug": "inland-sea-smallest-wide-nosym",
      "group": "Inland Sea",
      "variant": "",
      "title": "Inland Sea",
      "script": "Inland Sea",
      "mapClass": "MAPCLASS_MapScriptInlandSea2",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_WIDE",
      "aspectLabel": "Wide",
      "pointSymmetry": false,
      "mirror": true,
      "opts": [],
      "art": "img/maps/inland-sea.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-inland-sea-smallest-wide-nosym"
    },
    {
      "slug": "mountain-pass-smallest-wide-sym",
      "group": "Mountain Pass",
      "variant": "",
      "title": "Mountain Pass",
      "script": "Mountain Pass",
      "mapClass": "MAPCLASS_MapscriptMountainPass",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_WIDE",
      "aspectLabel": "Wide",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [],
      "art": "img/maps/mountain-pass.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-mountain-pass-smallest-wide-sym"
    },
    {
      "slug": "wetlands-smallest-square-sym",
      "group": "Wetlands",
      "variant": "",
      "title": "Wetlands",
      "script": "Wetlands",
      "mapClass": "MAPCLASS_MapscriptWetlands",
      "size": "MAPSIZE_SMALLEST",
      "sizeLabel": "Duel",
      "aspect": "MAPASPECTRATIO_SQUARE",
      "aspectLabel": "Square",
      "pointSymmetry": true,
      "mirror": true,
      "opts": [],
      "art": "img/maps/wetlands.png",
      "atlas": "https://alcaras.github.io/owtournamentatlas/#cfg-wetlands-smallest-square-sym"
    }
  ],
  "ffa": {
    "scripts": [
      {
        "name": "Archipelago",
        "mapClass": "MAPCLASS_MapScriptArchipelago",
        "art": "img/maps/archipelago.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-archipelago-huge-square"
      },
      {
        "name": "Arid Plateau",
        "mapClass": "MAPCLASS_AridPlateau",
        "art": "img/maps/arid-plateau.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-arid-plateau-huge-square"
      },
      {
        "name": "Bay",
        "mapClass": "MAPCLASS_MapScriptBay",
        "art": "img/maps/bay.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-bay-huge-square"
      },
      {
        "name": "Coastal Rain Basin",
        "mapClass": "MAPCLASS_CoastalRainBasin",
        "art": "img/maps/coastal-rain-basin.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-coastal-rain-basin-huge-square"
      },
      {
        "name": "Continent",
        "mapClass": "MAPCLASS_MapScriptContinent",
        "art": "img/maps/continent.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-continent-huge-square"
      },
      {
        "name": "Deep Jungle",
        "mapClass": "MAPCLASS_MapscriptJungle",
        "art": "img/maps/deep-jungle.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-deep-jungle-huge-square"
      },
      {
        "name": "Desert",
        "mapClass": "MAPCLASS_MapScriptDesert",
        "art": "img/maps/desert.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-desert-huge-square"
      },
      {
        "name": "Desolation",
        "mapClass": "MAPCLASS_MapScriptDesolation",
        "art": "img/maps/desolation.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-desolation-huge-square"
      },
      {
        "name": "Donut",
        "mapClass": "MAPCLASS_MapScriptDonut",
        "art": "img/maps/donut.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-donut-huge-square"
      },
      {
        "name": "Ebbing Sea",
        "mapClass": "MAPCLASS_MapScriptEbbingSea",
        "art": "img/maps/ebbing-sea.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-ebbing-sea-huge-square"
      },
      {
        "name": "Hardwood Forest",
        "mapClass": "MAPCLASS_MapScriptHardwoodForest",
        "art": "img/maps/hardwood-forest.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-hardwood-forest-huge-square"
      },
      {
        "name": "Highlands",
        "mapClass": "MAPCLASS_MapScriptHighlands",
        "art": "img/maps/highlands.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-highlands-huge-square"
      },
      {
        "name": "Inland Sea",
        "mapClass": "MAPCLASS_MapScriptInlandSea2",
        "art": "img/maps/inland-sea.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-inland-sea-huge-square"
      },
      {
        "name": "Lakes and Gulfs",
        "mapClass": "MAPCLASS_MapScriptLakesAndGulfs",
        "art": "img/maps/lakes-and-gulfs.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-lakes-and-gulfs-huge-square"
      },
      {
        "name": "Mediterranean",
        "mapClass": "MAPCLASS_MapScriptMediterranean",
        "art": "img/maps/mediterranean.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-mediterranean-huge-square"
      },
      {
        "name": "Mountain Pass",
        "mapClass": "MAPCLASS_MapscriptMountainPass",
        "art": "img/maps/mountain-pass.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-mountain-pass-huge-square"
      },
      {
        "name": "Multiple Continents",
        "mapClass": "MAPCLASS_MapScriptContinents",
        "art": "img/maps/multiple-continents.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-multiple-continents-huge-square"
      },
      {
        "name": "Northern Ocean",
        "mapClass": "MAPCLASS_MapScriptNorthernOcean",
        "art": "img/maps/northern-ocean.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-northern-ocean-huge-square"
      },
      {
        "name": "Player Islands",
        "mapClass": "MAPCLASS_MapScriptPlayerIslands",
        "art": "img/maps/player-islands.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-player-islands-huge-square"
      },
      {
        "name": "Seaside",
        "mapClass": "MAPCLASS_MapScriptSeaside",
        "art": "img/maps/seaside.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-seaside-huge-square"
      },
      {
        "name": "Wetlands",
        "mapClass": "MAPCLASS_MapscriptWetlands",
        "art": "img/maps/wetlands.png",
        "atlas": "https://alcaras.github.io/owffaatlas/#cfg-wetlands-huge-square"
      }
    ],
    "sizes": [
      {
        "id": "MAPSIZE_SMALL",
        "label": "Small"
      },
      {
        "id": "MAPSIZE_MEDIUM",
        "label": "Medium"
      },
      {
        "id": "MAPSIZE_LARGE",
        "label": "Large"
      },
      {
        "id": "MAPSIZE_HUGE",
        "label": "Huge"
      }
    ],
    "aspects": [
      {
        "id": "MAPASPECTRATIO_SQUARE",
        "label": "Square"
      },
      {
        "id": "MAPASPECTRATIO_WIDE",
        "label": "Wide"
      }
    ],
    "defaultSize": "MAPSIZE_HUGE",
    "defaultAspect": "MAPASPECTRATIO_SQUARE",
    "defaultPlayers": 10,
    "minPlayers": 3,
    "maxPlayers": 10
  }
};
